language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

install:
  - composer install

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict

script:
  phpunit

sudo: false

cache:
  directories:
    - node_modules
    - vendor
    - bower_components

webhooks:
  urls:
    - https://webhooks.gitter.im/e/31edf9087439c96470f5
  on_success: change
  on_failure: always
  on_start: false
