language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.4
      env: deps=low

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

env:
  global:
    - deps=no

script:
  phpunit

sudo: false

cache:
  directories:
    - node_modules
    - vendor
    - bower_components

webhooks:
  urls:
    - https://webhooks.gitter.im/e/31edf9087439c96470f5
  on_success: change
  on_failure: always
  on_start: false
