language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script: composer install --dev --prefer-source

sudo: false

cache:
    directories:
        - node_modules
        - vendor
        - bower_components

webhooks:
    urls:
        - https://webhooks.gitter.im/e/31edf9087439c96470f5
    on_success: change
    on_failure: always
    on_start: false
