language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

install:
  - if [ "$deps" = "no" ]; then export SYMFONY_DEPRECATIONS_HELPER=strict; fi;
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

env:
  global:
    - deps=no
    - SYMFONY_DEPRECATIONS_HELPER=weak

script:
  phpunit

sudo: false

cache:
  directories:
    - node_modules
    - vendor
    - bower_components

webhooks:
  urls:
    - https://webhooks.gitter.im/e/31edf9087439c96470f5
  on_success: change
  on_failure: always
  on_start: false
